[project]
name = "LLM-experiment"
version = "0.1.0"
description = "Add a short description here"
authors = ["Sébastien Boisgérault <Sebastien.Boisgerault@gmail.com>"]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]

[dependencies]
python = ">=3.12.2,<3.13"
chromadb = ">=0.4.24,<0.5"
nltk = ">=3.8.1,<3.9"
nltk_data = ">=2022.5.27,<2022.6"

[pypi-dependencies]
flet = "*"
ollama = "*"
requests = "*"
