[project]
name = "LLM-experiment"
version = "0.1.0"
description = "Add a short description here"
authors = ["Sébastien Boisgérault <Sebastien.Boisgerault@gmail.com>"]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]

[dependencies]
python = ">=3.12.2,<3.13"

[pypi-dependencies]
requests = "*"
flet = "*"
ollama = "*"
